name: Auto-merge Dependabot

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for patch-level updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
