name: Sync labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ops repo
        uses: actions/checkout@v4
        with:
          repository: adartem/adartem-ops
          path: ops

      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.ORG_PAT }}
          config-file: ops/.github/labels.yml
